<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="User-PC" name="Login" tests="1" failures="1" timestamp="11 May 2017 02:38:37 GMT" time="26.28" errors="0">
  <testcase name="LoginD" time="26.277" classname="Common.Login">
    <failure type="java.lang.AssertionError" message="Login Failed for:maym@inpods.com expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Failed for:maym@inpods.com expected [true] but found [false]
	at Common.Login.LoginD(Login.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginD -->
</testsuite> <!-- Login -->
